### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by makeri89** [ruusukivi/tsoha-cook-it#17]
# Vertaisarviointi

- Projekti näyttää olevan jo hyvällä mallilla

## Heroku

- Sivuston käyttö on helppoa
- `Search recipes` -näppäin ei toimi, joten se voisi olla hyvä piilottaa sivulta
- Uuden reseptin luominen onnistuu helposti, käyttöliittymä on selkeä
- Myöskään etusivun `What's trending` ja profiilisivun `Recipes liked` näppäimet eivät tee mitään, joten nekin voisi piilottaa kunnes niiden toiminnallisuus on toteutettu
- Ulkoasu on miellyttävä

## Koodi

- Koodi pääosin selkeää ja rakenteeltaan hyvää
- Jaettu järkevästi eri tiedostoihin

### `routes.py`

- Rekisteröitymislomakkeen salasanatarkistuksen voisi tehdä JavaScriptillä, jolloin virheviestin saa näkyviin esimerkiksi heti seuraavaan kenttään siirryttäessä ja lomaketta ei tarvitse ladata kokonaan uudelleen, jos esim. salasana on liian lyhyt
- Pieniä tyylivirheitä välilyöntien käytössä muuttujien sijoituksessa funktion kutsun nimetyiksi parametreiksi, ks. [materiaali](https://hy-tsoha.github.io/materiaali/tekninen_tarkastuslista/)

### `users.py`

- `logout` -funktio ei tyhjennä koko `session`ia
- `check_csrf` -funktiossa käytettyä `abort` -metodia ei ole määritelty (lisää flask importteihin)

### recipes.py

- Tietokannasta haetaan tietoa hienosti suoraan pelkillä SQL-komennoilla
- Funktioille voisi kuitenkin luoda docstring-kommentteja niissä olevien SQL-komentojen palauttaman sisällön helpompaa ymmärtämistä varten
- timestampin luominen onnistuu myös suoraan PostgreSQL:llä (`NOW()`)
- `get_recipes`-funktion viimeinen return on turha, sitä ei suoriteta koskaan

## Muuta

- HTML-templatet omaan silmään hyvin rakennettuja

**Comment by ruusukivi** [comment]
Kiitos, palaute oli todella hyödyllinen!
