### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by antonlep** [ruusukivi/tsoha-cook-it#25]
Sivusto toimii sulavasti ja on intuitiivinen käyttää. Reseptien lisääminen, poistaminen ja kommentointi toimii. Hakutoiminnasta pidin erityisesti. Whats buzzing kentän kanssa näytti olevan jotain  ongelmaa, se näytti tyhjää vaikka kommentoituja reseptejä olikin. Pieninä muotoseikkoina Add new comment kentässä lukee Title of recipe, tulee tavallaan kahteen kertaan. Sitten, like nappulaa painamalla uudestaan tykkäys häviää joka sinänsä on mielestäni loogista, mutta ehkä painikkeen nimeä voisi muuttaa samalla unlike että toiminta olisi selkeämpi?

Koodi on loogista ja selkeää. Yksi asia mikä osui omaan silmään, recipes taulussa on like_count ja comment_count kentät joita päivitetään, tuleeko tässä päällekkäisyyttä koska myös likes taulukossa on periaatteessa sama tieto tallessa? Muuten sql kyselyt on helppo ymmärtää, ja koodin jako moduuleihin vaikuttaa toimivalta.

**Comment by ruusukivi** [comment]
Kiitos paljon palautteesta! 

Päivitin sovellusta seuraavastI: https://github.com/ruusukivi/tsoha-cook-it/commit/8c721d91033560a7af2d35d998bdd23e119a79de

Tykkäysten ja kommenttien lukumäärän tuominen osaksi recipies-taulua on harkittu "rikos" - ajattelin, että on hyvä optimoida vähän listojen kokoamisen nopeutta tuomalla valmiiksi laskettu arvo osaksi recipies-taulua sen sijaan että se käytäisiin joka sivulatauksella laskemassa likes ja comments-tauluista jokaiselle listalle tulevalle receptille.
